project:
  type: website

website:
  title: "Project 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sample_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    codetools:
      code-block-border-left: "#31BAE9"
      code-block-bg: whitesmoke


